### ISSUE TITLE
Loading of datetimepicker is very slow

### ISSUE THREAD

**Issue by himavijayachandran** [katemihalikova/ionic-datetimepicker#1]
Loading of datetimepicker is very slow in android.It takes at least 2-3 seconds to load the picker.

**Comment by katemihalikova** [comment]
Works fine here, please provide more details.

**Comment by himavijayachandran** [comment]
I am using android 4.4.2. I checked with multiple devices having same version (4.4.2) of android. Slowness persists in all the devices.

**Comment by katemihalikova** [comment]
This version is not maintained anymore, please use Ionic Native with a plugin or use [ion-datetime-picker](https://github.com/katemihalikova/ion-datetime-picker).
